# Generated by Django 6.0.3 on 2026-03-21 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(help_text='SEC CIK identifier', max_length=20, unique=True)),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
                ('price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_facts_json', models.JSONField(blank=True, help_text='Full SEC XBRL response', null=True)),
                ('facts_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sec_edgar', 'SEC EDGAR'), ('yfinance', 'yfinance')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('records_created', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='stocks.company')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('revenue_growth_yoy', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('gross_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('operating_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('free_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='stocks.company')),
            ],
            options={
                'verbose_name_plural': 'stock metrics',
            },
        ),
        migrations.CreateModel(
            name='FinancialFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(db_index=True, max_length=50)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=10)),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_quarter', models.IntegerField(blank=True, null=True)),
                ('period_end_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit', models.CharField(default='USD', max_length=20)),
                ('form_type', models.CharField(blank=True, default='', max_length=10)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stocks.company')),
            ],
            options={
                'ordering': ['-fiscal_year', '-fiscal_quarter'],
                'indexes': [models.Index(fields=['company', 'metric', 'period_type'], name='stocks_fina_company_308569_idx'), models.Index(fields=['metric', 'fiscal_year'], name='stocks_fina_metric_c0a2aa_idx')],
                'unique_together': {('company', 'metric', 'period_type', 'fiscal_year', 'fiscal_quarter')},
            },
        ),
    ]
