# Generated by Django 6.0.3 on 2026-03-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_m2_schema_cut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIBudgetDay',
        ),
    ]
